scriptfields:
  - description: "Difference between updated date and created date in days"
    uuid: "c5f4766f-23d4-41bc-b4a9-07ed3f167165"
    name: "Date Difference"
    scriptedFieldType: "TEXT_FIELD"
    path: "CalculateDateDifference.groovy"

listeners:
  - description: "Add comment on issue creation with support SLA and documentation link"
    uuid: "9d114a5b-5a28-445f-acd9-5adbdcec1ab1"
    events:
      - jira:issue_created
    path: "CommentOnCreate.groovy"
    executionUser: ADD_ON
    projects:
      - "JRTWO"
  - description: "Add a definition of done checklist to an issue on creation"
    uuid: "625a3d1c-173a-4938-8874-08c4d05812ec"
    events:
      - jira:issue_created
    path: "DefinitionOfDoneListener.groovy"
    executionUser: ADD_ON
    projects:
      - "JRTWO"

jobs:
  - uuid: "1b22241f-ada9-4a4e-bce0-0de13a35074c"
    name: "Create time logging issue"
    cronExpression: "0 0 0 1 * ?"
    path: "CreateTimeLoggingIssue.groovy"
    atlassianUser:
      accountId: "557058:d2e5bd5c-dc49-41eb-a6f0-5e01093666c1"
    enabled: true
  - uuid: "301355c2-292a-43ab-81a6-8d4e6a8f9148"
    name: "Create Release"
    cronExpression: "0 0 0 1,15 * ?"
    path: "CreateRelease.groovy"
    atlassianUser:
      accountId: "557058:d2e5bd5c-dc49-41eb-a6f0-5e01093666c1"
    enabled: true

behaviours:
  - name: "Test"
    description: "My Behaviour"
    uuid: "d89c8588-a060-b07c-879f-98cff9c1d26b"
    enabled: true
    executionUser: ADD_ON
    config:
      - fieldName: ""
        fieldUuid: "81a205f1-721a-4627-a3f2-c9767e1e83c4"
        path: behaviourA.ts
        event:
          - "ONLOAD"
          - "ONCHANGE"
        viewTypes:
          - "GIC"
          - "IssueTransition"
          - "IssueView"
        affectedFields:
          - "summary"
      - fieldName: ""
        fieldUuid: "81a205f1-721a-4627-a3f2-c9767e1ex3c4"
        path: subpackagea/behaviourB.ts
        event:
          - "ONLOAD"
          - "ONCHANGE"
        viewTypes:
          # These are options from Atlassian's UI Modifications framework, determining where your Behaviour will run.
          # See https://developer.atlassian.com/platform/forge/manifest-reference/modules/jira-ui-modifications/
          - "GIC" # Global Issue Create page
          - "IssueTransition" # The new Jira issue transition experience - see https://community.atlassian.com/forums/Jira-articles/Now-GA-try-the-new-issue-transition-experience-in-Jira/ba-p/2734436
          - "IssueView"
        affectedFields:
          - "description"
    projects:
      - "10002" #TODO: These should be mappable from keys
    issueTypes:
      - "10005"
    mappings:
      "10002":
        - "10005"

workflows:
  - name: "Software Simplified Workflow for Project MARK1"
    transitions:
      - name: "In Progress"
        postFunctions:
          - parameters:
              id: "5a96894a-204c-416d-8d09-bbbfcb18b8a6"
              config:
                className: "com.adaptavist.sr.cloud.workflow.UpdateIssue"
                uuid: "79aecc0f-b4aa-454a-b91b-4a5c104eadda"
                enabled: true
                executionUser: "ADD_ON"
                condition: "true || false"
                description: "Add comment to issue"
                additionalCode: "Issues.getByKey(issue.key.toString()).addComment('Greetings from ScriptRunner')"
        conditions:
          - parameters:
              id: "4a2d7de4-3b95-40c5-b359-4dab3dd5824a"
              config:
                uuid: "7a46c9e7-9980-4164-8f85-4717b44fa9b1"
                description: "Check if any comments contain banned words"
                expression: "(issue.comments.filter(comment => comment.body.plainText.toLowerCase().includes('banned')).length <= 0)"
                enabled: true
        validators:
          - parameters:
              id: "b1340bfc-2003-41b2-9beb-621a266b489b"
              config:
                uuid: "5c3c30b5-a8e8-4d16-b5eb-c4f4a44fbcf8"
                description: "Check comments"
                expression: "(issue.comments.filter(comment => comment.body.plainText.toLowerCase().includes('banned')).length <= 0)"
                errorMessage: "No banned words in the comments."
                enabled: true
          - parameters:
              id: "414e3381-d974-4286-ac1e-ffa0f895770f"
              config:
                uuid: "46a851b6-a532-42c5-bd14-50cb6a235a98"
                description: "This will always be true. It's just an example. Insert your own validator here."
                expression: "true && !false"
                errorMessage: "If this failed ScriptRunner is broken."
                enabled: true
  - name: "PRAH: Project Management Workflow"
    transitions:
      - name: "Done"
        id: "21" # As a last resort, transitions with the same name can be distinguished by their ID. This is brittle, as IDs can vary between cloud instances for identical transitions.
        conditions:
          - parameters:
              id: "142b758a-5cf3-4619-bdd2-cc40219cc94d"
              config:
                uuid: "92246de9-f297-49de-9f04-750b7474a277"
                description: "Check if any comments contain disallowed words"
                expression: "(issue.comments.filter(comment => comment.body.plainText.toLowerCase().includes('disallowed')).length <= 0)"
                enabled: true
      - name: "Done"
        id: "41"
        conditions:
          - parameters:
              id: "b4fa9a4c-f580-4f97-a73f-d3c7471e62e7"
              config:
                uuid: "ead05c99-02fa-43ca-a703-9f1bc3187e04"
                description: "Check if the issue description contain disallowed words"
                expression: "!issue.description.plainText.includes('disallowed')"
                enabled: true
