scriptfields:
  - description: "Difference between updated date and created date in days"
    uuid: "c5f4766f-23d4-41bc-b4a9-07ed3f167165"
    name: "Date Difference"
    scriptedFieldType: "TEXT_FIELD"
    path: "CalculateDateDifference.groovy"

listeners:
  - description: "Add comment on issue creation with support SLA and documentation link"
    uuid: "9d114a5b-5a28-445f-acd9-5adbdcec1ab1"
    events:
      - jira:issue_created
    path: "CommentOnCreate.groovy"
    executionUser: ADD_ON
    projects:
      - "JRTWO"
  - description: "Add a definition of done checklist to an issue on creation"
    uuid: "625a3d1c-173a-4938-8874-08c4d05812ec"
    events:
      - jira:issue_created
    path: "DefinitionOfDoneListener.groovy"
    executionUser: ADD_ON
    projects:
      - "JRTWO"

jobs:
  - uuid: "1b22241f-ada9-4a4e-bce0-0de13a35074c"
    name: "Create time logging issue"
    cronExpression: "0 0 0 1 * ?"
    path: "CreateTimeLoggingIssue.groovy"
    atlassianUser:
      accountId: "557058:d2e5bd5c-dc49-41eb-a6f0-5e01093666c1"
    enabled: true
  - uuid: "301355c2-292a-43ab-81a6-8d4e6a8f9148"
    name: "Create Release"
    cronExpression: "0 0 0 1,15 * ?"
    path: "CreateRelease.groovy"
    atlassianUser:
      accountId: "557058:d2e5bd5c-dc49-41eb-a6f0-5e01093666c1"
    enabled: true

behaviours:
  - name: "Test"
    description: "My Behaviour"
    uuid: "d89c8588-a060-b07c-879f-98cff9c1d26b"
    enabled: true
    executionUser: ADD_ON
    config:
      - fieldName: ""
        fieldUuid: "81a205f1-721a-4627-a3f2-c9767e1e83c4"
        path: behaviourA.ts
        event:
          - "ONLOAD"
          - "ONCHANGE"
        viewTypes:
          - "GIC"
          - "IssueTransition"
          - "IssueView"
        affectedFields:
          - "summary"
      - fieldName: ""
        fieldUuid: "81a205f1-721a-4627-a3f2-c9767e1ex3c4"
        path: subpackagea/behaviourB.ts
        event:
          - "ONLOAD"
          - "ONCHANGE"
        viewTypes:
          # These are options from Atlassian's UI Modifications framework, determining where your Behaviour will run.
          # See https://developer.atlassian.com/platform/forge/manifest-reference/modules/jira-ui-modifications/
          - "GIC" # Global Issue Create page
          - "IssueTransition" # The new Jira issue transition experience - see https://community.atlassian.com/forums/Jira-articles/Now-GA-try-the-new-issue-transition-experience-in-Jira/ba-p/2734436
          - "IssueView"
        affectedFields:
          - "description"
    projects:
      - "10002" #TODO: These should be mappable from keys
    issueTypes:
      - "10005"
    mappings:
      "10002":
        - "10005"
